- name: Supprimer la page par défaut de Nginx
  file:
    path: /var/www/html/index.nginx-debian.html
    state: absent

- name: Installer Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Déployer la page web personnalisée
  copy:
    src: index.html
    dest: /var/www/html/index.html
    owner: www-data
    group: www-data
    mode: '0644'

- name: Redémarrer Nginx
  service:
    name: nginx
    state: restarted
